package kirjahylly.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import kirjahylly.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.20 21:08:48 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjahyllyTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa33 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa33() throws SailoException {    // Kirjahylly: 33
    Kirjahylly kirjahylly = new Kirjahylly(); 
    Kirja kirja1 = new Kirja(), kirja2 = new Kirja(); 
    kirjahylly.lisaa(kirja1); 
    kirjahylly.lisaa(kirja2); 
    kirjahylly.lisaa(kirja1); 
    Collection<Kirja> loytyneet = kirjahylly.etsi("",1); 
    Iterator<Kirja> it = loytyneet.iterator(); 
    assertEquals("From: Kirjahylly line: 42", kirja1, it.next()); 
    assertEquals("From: Kirjahylly line: 43", kirja2, it.next()); 
    assertEquals("From: Kirjahylly line: 44", kirja1, it.next()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaKirjailijat66 */
  @Test
  public void testAnnaKirjailijat66() {    // Kirjahylly: 66
    Kirjahylly kirjahylly = new Kirjahylly(); 
    Kirja kirja1 = new Kirja(), kirja2 = new Kirja(), kirja3 = new Kirja(); 
    kirja1.rekisteroi(); kirja2.rekisteroi(); kirja3.rekisteroi(); 
    int id1 = kirja1.getTunnusNro(); 
    int id2 = kirja2.getTunnusNro(); 
    Kirjailija kirj21 = new Kirjailija(id2); kirjahylly.lisaa(kirj21); 
    Kirjailija kirj11 = new Kirjailija(id1); kirjahylly.lisaa(kirj11); 
    Kirjailija kirj22 = new Kirjailija(id2); kirjahylly.lisaa(kirj22); 
    Kirjailija kirj12 = new Kirjailija(id1); kirjahylly.lisaa(kirj12); 
    Kirjailija kirj23 = new Kirjailija(id2); kirjahylly.lisaa(kirj23); 
    List<Kirjailija> loytyneet; 
    loytyneet = kirjahylly.annaKirjailijat(kirja3); 
    assertEquals("From: Kirjahylly line: 83", 0, loytyneet.size()); 
    loytyneet = kirjahylly.annaKirjailijat(kirja1); 
    assertEquals("From: Kirjahylly line: 85", 2, loytyneet.size()); 
    assertEquals("From: Kirjahylly line: 86", true, loytyneet.get(0) == kirj11); 
    assertEquals("From: Kirjahylly line: 87", true, loytyneet.get(1) == kirj12); 
    loytyneet = kirjahylly.annaKirjailijat(kirja2); 
    assertEquals("From: Kirjahylly line: 89", 3, loytyneet.size()); 
    assertEquals("From: Kirjahylly line: 90", false, loytyneet.get(0) == kirj23); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaKirjailijat102 */
  @Test
  public void testAnnaKirjailijat102() {    // Kirjahylly: 102
    Kirjahylly kirjahylly = new Kirjahylly(); 
    Kirja kirja1 = new Kirja(), kirja2 = new Kirja(), kirja3 = new Kirja(); 
    kirja1.rekisteroi(); kirja2.rekisteroi(); kirja3.rekisteroi(); 
    int id1 = kirja1.getTunnusNro(); 
    int id2 = kirja2.getTunnusNro(); 
    Kirjailija kirj21 = new Kirjailija(id2); kirjahylly.lisaa(kirj21); 
    Kirjailija kirj11 = new Kirjailija(id1); kirjahylly.lisaa(kirj11); 
    Kirjailija kirj22 = new Kirjailija(id2); kirjahylly.lisaa(kirj22); 
    Kirjailija kirj12 = new Kirjailija(id1); kirjahylly.lisaa(kirj12); 
    Kirjailija kirj23 = new Kirjailija(id2); kirjahylly.lisaa(kirj23); 
    List<Kirjailija> loytyneet; 
    loytyneet = kirjahylly.annaKirjailijat(); 
    assertEquals("From: Kirjahylly line: 119", 5, loytyneet.size()); 
    assertEquals("From: Kirjahylly line: 120", true, loytyneet.get(0) == kirj21); 
    assertEquals("From: Kirjahylly line: 121", true, loytyneet.get(3) == kirj12); 
    assertEquals("From: Kirjahylly line: 122", false, loytyneet.get(0) == kirj23); 
    loytyneet = kirjahylly.annaKirjailijat(kirja1); 
    assertEquals("From: Kirjahylly line: 124", true, loytyneet.get(1) == kirj12); 
  } // Generated by ComTest END
}