package kirjahylly.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import kirjahylly.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.24 17:37:33 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjahyllyTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa33 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa33() throws SailoException {    // Kirjahylly: 33
    Kirjahylly kirjahylly = new Kirjahylly(); 
    Kirja kirja1 = new Kirja(), kirja2 = new Kirja(); 
    kirjahylly.lisaa(kirja1); 
    kirjahylly.lisaa(kirja2); 
    kirjahylly.lisaa(kirja1); 
    Collection<Kirja> loytyneet = kirjahylly.etsi("",1); 
    Iterator<Kirja> it = loytyneet.iterator(); 
    assertEquals("From: Kirjahylly line: 42", kirja1, it.next()); 
    assertEquals("From: Kirjahylly line: 43", kirja2, it.next()); 
    assertEquals("From: Kirjahylly line: 44", kirja1, it.next()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaKirjailijat66 */
  @Test
  public void testAnnaKirjailijat66() {    // Kirjahylly: 66
    Kirjahylly kirjahylly = new Kirjahylly(); 
    Kirjailija kirj21 = new Kirjailija("Harari"); kirj21.rekisteroi(); kirjahylly.lisaa(kirj21); 
    Kirjailija kirj11 = new Kirjailija("Austen"); kirj11.rekisteroi(); kirjahylly.lisaa(kirj11); 
    Kirjailija kirj22 = new Kirjailija("Shelley"); kirj22.rekisteroi(); kirjahylly.lisaa(kirj22); 
    int id1 = kirj21.getTunnusNro(); 
    int id2 = kirj11.getTunnusNro(); 
    Kirja kirja1 = new Kirja(), kirja2 = new Kirja(), kirja3 = new Kirja(); 
    kirja1.lisaaKirjailija(id1); kirja2.lisaaKirjailija(id2); 
    kirja1.rekisteroi(); kirja2.rekisteroi(); kirja3.rekisteroi(); 
    kirja3.lisaaKirjailija(id1); 
    List<Kirjailija> loytyneet; 
    loytyneet = kirjahylly.annaKirjailijat(kirja3); 
    assertEquals("From: Kirjahylly line: 84", 1, loytyneet.size()); 
    loytyneet = kirjahylly.annaKirjailijat(kirja1); 
    assertEquals("From: Kirjahylly line: 86", 1, loytyneet.size()); 
    assertEquals("From: Kirjahylly line: 87", true, loytyneet.get(0) == kirj21); 
    loytyneet = kirjahylly.annaKirjailijat(kirja2); 
    assertEquals("From: Kirjahylly line: 89", 1, loytyneet.size()); 
    assertEquals("From: Kirjahylly line: 90", false, loytyneet.get(0) == kirj22); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaKirjailijat102 */
  @Test
  public void testAnnaKirjailijat102() {    // Kirjahylly: 102
    Kirjahylly kirjahylly = new Kirjahylly(); 
    Kirjailija kirj25 = new Kirjailija("Harari"); kirj25.rekisteroi(); kirjahylly.lisaa(kirj25); 
    Kirjailija kirj18 = new Kirjailija("Austen"); kirj18.rekisteroi(); kirjahylly.lisaa(kirj18); 
    Kirjailija kirj26 = new Kirjailija("Shelley"); kirj26.rekisteroi(); kirjahylly.lisaa(kirj26); 
    List<Kirjailija> loytyneet; 
    loytyneet = kirjahylly.annaKirjailijat(); 
    assertEquals("From: Kirjahylly line: 113", 3, loytyneet.size()); 
    assertEquals("From: Kirjahylly line: 114", true, loytyneet.get(0) == kirj25); 
    assertEquals("From: Kirjahylly line: 115", true, loytyneet.get(2) == kirj26); 
    assertEquals("From: Kirjahylly line: 116", false, loytyneet.get(0) == kirj18); 
  } // Generated by ComTest END
}