package kirjahylly.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjahylly.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.31 14:23:05 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjailijaTest {



  // Generated by ComTest BEGIN
  /** testGetNimi41 */
  @Test
  public void testGetNimi41() {    // Kirjailija: 41
    Kirjailija sapiens = new Kirjailija("Shelley"); 
    { String _l_=sapiens.getNimi(),_r_="Shelley"; if ( !_l_.matches(_r_) ) fail("From: Kirjailija line: 43" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi81 */
  @Test
  public void testRekisteroi81() {    // Kirjailija: 81
    Kirjailija kirj = new Kirjailija(); 
    assertEquals("From: Kirjailija line: 83", 0, kirj.getTunnusNro()); 
    kirj.rekisteroi(); 
    Kirjailija kirja = new Kirjailija(); 
    kirja.rekisteroi(); 
    int n1 = kirj.getTunnusNro(); 
    int n2 = kirja.getTunnusNro(); 
    assertEquals("From: Kirjailija line: 89", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString123 */
  @Test
  public void testToString123() {    // Kirjailija: 123
    Kirjailija kirjailija = new Kirjailija(); 
    kirjailija.parse("   2   | Yuval Noah Harari"); 
    assertEquals("From: Kirjailija line: 126", "2|Yuval Noah Harari", kirjailija.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse140 */
  @Test
  public void testParse140() {    // Kirjailija: 140
    Kirjailija kirjailija = new Kirjailija(); 
    kirjailija.parse("   2   | Yuval Noah Harari"); 
    assertEquals("From: Kirjailija line: 143", "2|Yuval Noah Harari", kirjailija.toString()); 
    kirjailija.rekisteroi(); 
    int n = kirjailija.getTunnusNro(); 
    kirjailija.parse(""+(n+20)); 
    kirjailija.rekisteroi(); 
    assertEquals("From: Kirjailija line: 149", n+20+1, kirjailija.getTunnusNro()); 
    assertEquals("From: Kirjailija line: 150", "" + (n+20+1) + "|Yuval Noah Harari", kirjailija.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta241 */
  @Test
  public void testAseta241() {    // Kirjailija: 241
    Kirjailija kirjailija = new Kirjailija(); 
    assertEquals("From: Kirjailija line: 243", null, kirjailija.aseta(1,"Harari")); 
    assertEquals("From: Kirjailija line: 244", "Vain kirjaimia ja '-' nimeen", kirjailija.aseta(1,"24")); 
    assertEquals("From: Kirjailija line: 245", null, kirjailija.aseta(1,"Mörkö")); 
  } // Generated by ComTest END
}