package kirjahylly.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjahylly.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.20 21:08:31 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjailijaTest {



  // Generated by ComTest BEGIN
  /** testGetNimi64 */
  @Test
  public void testGetNimi64() {    // Kirjailija: 64
    Kirjailija sapiens = new Kirjailija("Shelley"); 
    { String _l_=sapiens.getNimi(),_r_="Shelley"; if ( !_l_.matches(_r_) ) fail("From: Kirjailija line: 66" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi114 */
  @Test
  public void testRekisteroi114() {    // Kirjailija: 114
    Kirjailija kirj = new Kirjailija(); 
    assertEquals("From: Kirjailija line: 116", 0, kirj.getTunnusNro()); 
    kirj.rekisteroi(); 
    Kirjailija kirja = new Kirjailija(); 
    kirja.rekisteroi(); 
    int n1 = kirj.getTunnusNro(); 
    int n2 = kirja.getTunnusNro(); 
    assertEquals("From: Kirjailija line: 122", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString165 */
  @Test
  public void testToString165() {    // Kirjailija: 165
    Kirjailija kirjailija = new Kirjailija(); 
    kirjailija.parse("   2   | 4 | Yuval Noah Harari"); 
    assertEquals("From: Kirjailija line: 168", "2|4|Yuval Noah Harari", kirjailija.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse182 */
  @Test
  public void testParse182() {    // Kirjailija: 182
    Kirjailija kirjailija = new Kirjailija(); 
    kirjailija.parse("   2   | 4 | Yuval Noah Harari"); 
    assertEquals("From: Kirjailija line: 185", 4, kirjailija.getKirjaNro());
    assertEquals("From: Kirjailija line: 186", "2|4|Yuval Noah Harari", kirjailija.toString()); 
    kirjailija.rekisteroi(); 
    int n = kirjailija.getTunnusNro(); 
    kirjailija.parse(""+(n+20)); 
    kirjailija.rekisteroi(); 
    assertEquals("From: Kirjailija line: 192", n+20+1, kirjailija.getTunnusNro()); 
    assertEquals("From: Kirjailija line: 193", "" + (n+20+1) + "|4|Yuval Noah Harari", kirjailija.toString()); 
  } // Generated by ComTest END
}