package kirjahylly.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjahylly.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.06.30 16:18:30 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjailijaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi71 */
  @Test
  public void testRekisteroi71() {    // Kirjailija: 71
    Kirjailija kirj = new Kirjailija(); 
    assertEquals("From: Kirjailija line: 73", 0, kirj.getTunnusNro()); 
    kirj.rekisteroi(); 
    Kirjailija kirja = new Kirjailija(); 
    kirja.rekisteroi(); 
    int n1 = kirj.getTunnusNro(); 
    int n2 = kirja.getTunnusNro(); 
    assertEquals("From: Kirjailija line: 79", n2-1, n1); 
  } // Generated by ComTest END
}