package kirjahylly.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjahylly.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.06.30 16:17:12 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjaTest {


  // Generated by ComTest BEGIN
  /** testGetNimi33 */
  @Test
  public void testGetNimi33() {    // Kirja: 33
    Kirja sapiens = new Kirja(); 
    sapiens.taytaSapiensTiedoilla(); 
    { String _l_=sapiens.getNimi(),_r_="Sapiens: Ihmisen lyhyt historia .*"; if ( !_l_.matches(_r_) ) fail("From: Kirja line: 36" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi105 */
  @Test
  public void testRekisteroi105() {    // Kirja: 105
    Kirja sapiens = new Kirja(); 
    assertEquals("From: Kirja line: 107", 0, sapiens.getTunnusNro()); 
    sapiens.rekisteroi(); 
    Kirja frankenstein = new Kirja(); 
    frankenstein.rekisteroi(); 
    int n1 = sapiens.getTunnusNro(); 
    int n2 = frankenstein.getTunnusNro(); 
    assertEquals("From: Kirja line: 113", n2-1, n1); 
  } // Generated by ComTest END
}