package kirjahylly.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjahylly.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.06.30 16:16:56 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa31 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa31() throws SailoException {    // Kirjat: 31
    Kirjat kirjat = new Kirjat(); 
    Kirja kirja1 = new Kirja(), kirja2 = new Kirja(); 
    assertEquals("From: Kirjat line: 35", 0, kirjat.getLkm()); 
    kirjat.lisaa(kirja1); assertEquals("From: Kirjat line: 36", 1, kirjat.getLkm()); 
    kirjat.lisaa(kirja2); assertEquals("From: Kirjat line: 37", 2, kirjat.getLkm()); 
    kirjat.lisaa(kirja1); assertEquals("From: Kirjat line: 38", 3, kirjat.getLkm()); 
    assertEquals("From: Kirjat line: 39", kirja1, kirjat.anna(0)); 
    assertEquals("From: Kirjat line: 40", kirja2, kirjat.anna(1)); 
    assertEquals("From: Kirjat line: 41", kirja1, kirjat.anna(2)); 
    assertEquals("From: Kirjat line: 42", false, kirjat.anna(1) == kirja1); 
    assertEquals("From: Kirjat line: 43", true, kirjat.anna(1) == kirja2); 
    try {
    assertEquals("From: Kirjat line: 44", kirja1, kirjat.anna(3)); 
    fail("Kirjat: 44 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    kirjat.lisaa(kirja1); assertEquals("From: Kirjat line: 45", 4, kirjat.getLkm()); 
    kirjat.lisaa(kirja1); assertEquals("From: Kirjat line: 46", 5, kirjat.getLkm()); 
    kirjat.lisaa(kirja1); assertEquals("From: Kirjat line: 47", 6, kirjat.getLkm()); 
    kirjat.lisaa(kirja1); assertEquals("From: Kirjat line: 48", 7, kirjat.getLkm()); 
    kirjat.lisaa(kirja1); assertEquals("From: Kirjat line: 49", 8, kirjat.getLkm()); 
    try {
    kirjat.lisaa(kirja1); 
    fail("Kirjat: 50 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}